# Prohibit general access to this service.
#restrict default ignore // Removed this configuration since it restricts all communication 
 
restrict default -4 nomodify nopeer noquery notrap 
restrict default -6 nomodify nopeer noquery notrap 
 
restrict 127.0.0.1 
restrict ::1 
 
tinker panic 0 
driftfile /var/run/ntp.drift
server pool.ntp.org
server time.nist.gov
