server.modules += ( "mod_proxy" )

$HTTP["url"] =~ "^/bios/" {
    setenv.add-response-header += ( "Content-Encoding" => "gzip")
    server.error-handler-404 = "/"
}

proxy.server  = ( "/redfish" => ( ( "host" => "127.0.0.1", "port" => 9080 )) )

$SERVER["socket"] == ":443" {
    ssl.cipher-list += " AES256:HIGH"
    ssl.ca-file = "/conf/ca.pem"
    ssl.verifyclient.activate = "enable"
    ssl.verifyclient.enforce = "disable"
    ssl.verifyclient.username = "SSL_CLIENT_S_DN_CN"
    ssl.verifyclient.exportcert= "enable"
}