# Debug Level : 0 is NO Debug, 2 is highest level
DEBUGLEVEL=0
# Directory to drop off the Debug file in, File is named
DEBUGDIR=/var/log/
# Append the log messages to existsing log file if it exists
OVERWRITE=1
I2C_DRIVER_NAME=/dev/i2c2

# Avago Vendor ID
VENDORID=0x1000
# Gen-3 IT Controller device IDs list
# 0x97 3008
# 0x90 3108
DEVICEIDS=0x97 0x90
# Enclosure events polling interval in minutes
ENCLOSUREPOLLING=0
# States this is an OOB build
OOB=1
# Maximum I2C Buffer size for Writes from BMC to Controller
I2CMAXWRITESIZE=64
# Maximum I2C Buffer size for Reads to BMC from Controller
I2CMAXREADSIZE=64
# Maximum size, (unused variable)
I2CMAXREADWRITESIZE=65
# I2C BMC address - OEM provided information
I2CBMCI2CADDRESS=16
# Number of retries to be done at lowest I2C layer in case of error
I2C_RETRY_COUNT=5
# Delay after sending last write, and before sending first I2C Read
# This delay will be for all non-SCSI requests.  Time is in milliseconds
I2C_DELAY_FOR_CONFIG=25
# Delay after sending last write, and before sending first I2C Read
# This delay will be for all SCSI commands.  Time is in milliseconds
# Pick a value that gives SCSI commands time to complete the majority of the time
# This will cutdown on I2C retries
I2C_DELAY_FOR_DRIVE=25
# Firmware events polling interval in seconds
I2C_FW_EVENTS_POLL_INTERVAL=5
# Enclosure Event Polling Timer (and Poll for drive FW change) in seconds
# value of 0 means no polling
ENCLOSURE_POLLING=0
