#############################################################################
# Default syslog-ng.conf file which collects all local logs into a
# single file called /var/log/messages.
#

@version: 3.38
#@include "scl.conf"

template format_console{template("${MESSAGE}\n");};
template format_bmc_log{template("${DATE} ${PROGRAM} ${PID} ${MESSAGE}\n");};

source bmc_log {unix-dgram("/var/log/log");};

filter f_bmc_all {facility(kern, user, daemon, local0);};
filter f_local0 {facility(local0);};
filter f_daemon {facility(daemon);};
filter f_local2 {facility(local2);};

destination d_bmc_all {file("/var/log/messages" template(format_bmc_log));};
destination d_console {file("/dev/console" template(format_console));};
destination d_daemon {file("/var/log/daemon.log" template(format_bmc_log));};
#destination d_center_log_server {udp("192.168.1.1", port(514));};

log {source(bmc_log); filter(f_bmc_all); destination(d_bmc_all);};
log {source(bmc_log); filter(f_local0); destination(d_console);};
log {source(bmc_log); filter(f_daemon); destination(d_daemon);};
#log {source(bmc_log); filter(f_local2); destination(d_center_log_server);};
