# the first system should be the G4 as the user profiles and the network configuration will be
# discovered from here only................

[system1]
	#indcates the ip of G4, must if medium is network
	ip = 127.0.0.1
	portnumber = 623
	username = admin
	# can be either network/IPMB
	medium = network
	# can be either none/rmcp/reserved/oem/straight
	authenticationtype = rmcp
	# can be either proprietary/admin/operator/user/callback/reserved
	privilegelevel = admin

