server.document-root        = "/usr/local/www"
server.pid-file = "/var/run/lighttpd.pid"

# files to check for if .../ is requested
index-file.names            = ( "home.html","index.php", "index.html",
                                "index.htm", "default.htm", "index.html.gz","viewer.html")

server.error-handler-404 = "/index.html"

server.max-read-idle = 120
server.max-keep-alive-idle = 120

server.port = 443                                        
ssl.engine = "enable"                                                                     
server.use-ipv6 = "enable"                            
ssl.cipher-list = "TLSv1+HIGH !SSLv2 !RC4 !aNULL !eNULL !3DES @STRENGTH"
ssl.pemfile = "/conf/server.pem"

# mimetype mapping
mimetype.assign             = (
  ".gif"          =>      "image/gif",
  ".jpg"          =>      "image/jpeg",
  ".jpeg"         =>      "image/jpeg",
  ".png"          =>      "image/png",
  ".css"          =>      "text/css",
  ".html"         =>      "text/html",
  ".htm"          =>      "text/html",
  ".js"           =>      "text/javascript",
  ".text"         =>      "text/plain",
  ".txt"          =>      "text/plain",
  ".xml"          =>      "text/xml",
  ".elg"          =>      "application/x-ibmclog",
  ".jnlp"         =>      "application/x-java-jnlp-file",
  ".gz"       =>    "application/x-gzip",
  ".tar.gz"   =>    "application/x-gzip-compressed-tar"  
 )

include "redfish_lighttpd.conf"
